spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cdrdb
    username: postgres
    password: Pratik@2003
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080
